### ISSUE TITLE
bad variable name

### ISSUE THREAD

**Issue by Ayamin0x539** [Catastrio/Twitch-Follower-Grabber#7]
https://github.com/Catastrio/Twitch-Follower-Grabber/blob/e4c177b7c59b3c431e033e6e4d8aad5377917a23/TwitchFollowerGrabber.py#L19

"userLoginId" makes me think the variable is of type integer. But it isn't, is it? What does this json object look like? Can you think of a better name?

**Comment by Catastrio** [comment]
You'll have to offer me some insight here. Using my name, Catastrio, would get me the ID "40279644" which is technically an integer. Though, the JSON object gives it to me as a string. 

If you have anymore tips here, let me know. 

userLoginId seems best to me because, following the code:
1. User inputs a loginName after prompted.
2. userLoginEndpoint generated by link + loginName
3. userLoginResponse stores a requests.get() call on the userLoginEndpoint.
4. userLoginID stores the ID that we've pulled from the plain text loginName provided in step 1 from userLoginResponse.

I think if any updates should be made it should be loginName to userLoginName and userLoginID to userLoginNameID yeah? That way we can follow, logically, how we got to that id from user provided input.

**Comment by Catastrio** [comment]
I thought about this some more while I was doing other things. You mention type.

Do you think I should rename it to userLoginIDString so that I know how to use it in future parts of the program?

**Comment by Ayamin0x539** [comment]
Look at the example response:
```json
{"data":[{
   "id":"44322889",
   "login":"dallas",
   "display_name":"dallas",
   "type":"staff",
   "broadcaster_type":"",
   "description":"Just a gamer playing games and chatting. :)",
   "profile_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/dallas-profile_image-1a2c906ee2c35f12-300x300.png",
   "offline_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/dallas-channel_offline_image-1a2c906ee2c35f12-1920x1080.png",
   "view_count":191836881,
   "email":"login@provider.com"
}]}
```

The "id" field has a string. Notice the quotes around `44322889`. On the other hand. "view_count" comes back as an integer. Note the lack of quotes.

Get rid of the word "login". This has nothing to do with actually "logging in". It's just the user ID of that particular user. "login" is the parameter name for the request to the "users?" method.
